image: 'public.ecr.aws/docker/library/node:18-bullseye'

stages:
  - build
  - test
  # - deploy

# default:
#   cache:
#     key:
#       files:
#         - pnpm-lock.yaml
#     paths:
#       - .pnpm-store
    

build:
  stage: build
  before_script:
    - corepack enable
    - corepack prepare --activate
    - pnpm config set store-dir .pnpm-store
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    paths:
      - dist/

  
e2e-test:
  stage: test
  # image: mcr.microsoft.com/playwright:v1.44.0-jammy
  before_script:
    - corepack enable
    - corepack prepare --activate
    - pnpm config set store-dir .pnpm-store
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  script:
    - pnpm install
    - pnpm exec nx run e2e-ui-reporter 
  allow_failure: true
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 2 days

  # parallel:
  #   matrix:
  #     - PROJECT: ['chromium']
  #       SHARD: ['1/10', '2/10', '3/10', '4/10', '5/10', '6/10', '7/10', '8/10', '9/10', '10/10']
