build:
  stage: build
  only:
    - merge_requests
  before_script:
    - echo $SOURCE
    - corepack enable
    - corepack prepare --activate
    - pnpm config set store-dir .pnpm-store
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  script:
    - chmod +x ./scripts/test.sh
    - ./scripts/test.sh
    - pnpm install
    - pnpm run build
  artifacts:
    paths:
      - dist/
