test:
  script:
    - npm install
    - npm run test
  parallel:
    matrix:
      - NODE_VERSION: ["14", "16"]
        OS: ["ubuntu-20.04", "linux"]
  variables:
    NODE_VERSION: $NODE_VERSION
    OS: $OS
    